### PR TITLE
Fix for #1147, Proxy for audio URL and upgrade hls.js

### PR DESCRIPTION
**Pull request by jackyzy823**
Fix for #1147, 
1. Proxy for audio URL in `cmaf` container
2. Upgrade `hls.js` to 1.5.1 and use full version

-----
Or , we could force using `container=fmp4` instead of c`ontainer=cmaf`

### CODE REVIEW

**Comment by zedeus** [comment]
Thank you for the quick fix, but I'd like to avoid the larger hls.js file and stick with the previous behavior. I've pushed a simple fix to force fmp4.

**Comment by jackyzy823** [comment]
It's ok for me.  Just afraid that twitter might drop `fmp4` support in the feature.

**Comment by jackyzy823** [comment]
> Just afraid that twitter might drop `fmp4` support in the feature.

Sadly, It happened. event using fmp4 in the query , it still returns m3u8 with cmaf format.

But whatever.

**Comment by zedeus** [comment]
Getting complaints about broken videos, and this supposedly fixes it. Can you reopen and rebase please?

**Pull request closed without merging**
