### PR TITLE
Expand acronym

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by kokocivikcv** [comment]
https://PolygonScan.io/
@kokocivikcv19

**Comment by zedeus** [comment]
It's not for live streaming so that makes it more confusing. It's not important what hls means.

**Comment by vanillajonathan** [comment]
Then it should at least be uppercased so that it is obvious that is an acronym and not a misspelled word.

**Comment by zedeus** [comment]
Done

**Pull request closed without merging**
