### PR TITLE
Add dracula theme

### PR DESCRIPTION
**Pull request by wasi-master**
Adds the [dracula color scheme](https://en.wikipedia.com/wiki/Dracula_(color_scheme)) to nitter.

Dracula theme is currently available for more than 257 apps and websites

### CODE REVIEW

**Comment by zedeus** [comment]
Thanks! Can you show a screenshot of the theme?

**Comment by wasi-master** [comment]
@zedeus of course

image
image
image

**Comment by zedeus** [comment]
Looks nice, though I do notice some missing contrast:
image
image
image

I think this will also affect some other elements like cards and images. Take for example these two:
https://nitter.net/Axiom_Space/status/1504837154387673114#m
image

https://nitter.net/SpaceX/status/1499445667088912404#m
image

**Comment by wasi-master** [comment]
@zedeus I tried to keep it as close as the [official guidelines for the dracula theme](https://draculatheme.com/contribute). But after tweaking the contrast a bit, I came up with these, do you want more contrast?

image
image
image

If these are okay then I'll push these, otherwise I don't know really

**Comment by zedeus** [comment]
Looks good to me!

**Comment by wasi-master** [comment]
@zedeus done :)

**Comment by zedeus** [comment]
Thanks!

**Pull request merged**
