### PR TITLE
Remove not used dependency in Dockerfile

### PR DESCRIPTION
**Pull request by PeterDaveHello**
These packages seem to be unnecessary in the Dockerfile

### CODE REVIEW

**Comment by HeavenVolkoff** [comment]
I think `libffi-dev` `openssl-dev` are also not needed or are already included in nim base image, as I am able to build nitter without them.

**Comment by PeterDaveHello** [comment]
Thanks @HeavenVolkoff , let me test it and update the PR!

**Comment by selurvedu** [comment]
You can also replace `pcre-dev` with `pcre` as it pulls much less dependencies, saving 5 MiB:

```
/src # apk add pcre-dev
(1/8) Installing libpcre16 (8.44-r0)
(2/8) Installing libpcre32 (8.44-r0)
(3/8) Installing libgcc (10.3.1_git20210424-r2)
(4/8) Installing pcre (8.44-r0)
(5/8) Installing libstdc++ (10.3.1_git20210424-r2)
(6/8) Installing libpcrecpp (8.44-r0)
(7/8) Installing pkgconf (1.7.4-r0)
(8/8) Installing pcre-dev (8.44-r0)
Executing busybox-1.33.1-r3.trigger
OK: 14 MiB in 25 packages
```

```
/src # apk add pcre
(1/1) Installing pcre (8.44-r0)
OK: 9 MiB in 18 packages
```

```
/src # apk del pcre-dev
...
/src # ./start.sh
nohup: appending output to nohup.out
could not load: libpcre.so(.3|.1|)
(compile with -d:nimDebugDlOpen for more information)
/src # apk add pcre
(1/1) Installing pcre (8.44-r0)
OK: 9 MiB in 18 packages
/src # ./start.sh
nohup: appending output to nohup.out
Starting Nitter at http://nitter.net
Connected to Redis at localhost:6379
```

**Comment by PeterDaveHello** [comment]
@selurvedu cool, I'll test if everything still works good with this change!

**Comment by PeterDaveHello** [comment]
@zedeus with all due respect, 204b3e9e786b5f976315e5f152b076eafc728ebe is very contributor not friendly.

**Comment by zedeus** [comment]
@PeterDaveHello I'm sorry, I think there was a merge conflict and at first I did some other changes beyond the scope of your PR.

**Pull request closed without merging**
